pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash

  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
    actions:
      merge:
        method: squash

  - name: automatic merge for Renovate pull requests
    conditions:
      - author=renovate[bot]
    actions:
      merge:
        method: squash
